par(mfrow=c(1,1))
library(tseries)
library(xts)
library(zoo)
library(quantmod)
library(dplyr)
library(forecast)
library(ggplot2)
library(rio)
library(tidyverse)

stock<-getSymbols('CENX', from = '2010-01-01', src = 'yahoo', auto.assign = FALSE)

stock_close <- stock[,4]
stock_close_ma7 <- ma(stock_close,order = 7, frequency==1)
stock_close_ma20 <- ma(stock_close,order = 20)
stock_close_ma7_ts<-ts(data = stock_close_ma7)


plot(stock_close)
plot(stock_close_ma7)
plot(stock_close_ma20)


count_ma <- ts(data = stock_close_ma7_ts, frequency=10)

stock_ma7_decomp <- decompose(stock_close_ma7_ts)

deseasonal_cnt <- seasadj(stock_ma7_decomp)

plot(decomp)
plot(deseasonal_cnt)

adf.test(stock_close, k=255)

stock_close_d1 <- diff(stock_close, differences=1)
adf.test(stock_close_ts_d1, k=255)

stock_close_d2 <- diff(stock_close, differences=2)
adf.test(stock_close_ts_d2, k=255)

stock_close_d3 <- diff(stock_close, differences=3)
adf.test(stock_close_ts_d3, k=255)

stock_close_d4 <- diff(stock_close, differences=4)
adf.test(stock_close_ts_d4, k=255)

stock_close_d5 <- diff(stock_close, differences=5)
adf.test(stock_close_ts_d4, k=255)

stock_close_d6 <- diff(stock_close, differences=6)
adf.test(stock_close_ts_d4, k=255)

plot(stock_close_d1)
plot(stock_close_d2)
plot(stock_close_d3)
plot(stock_close_d4)
plot(stock_close_d5)
plot(stock_close_d6)

auto.arima(stock_close, seasonal = F)


Acf(stock_close_ts, main='ACF for differenced series')
Pacf(stock_close_ts, main='PACF for differenced series')


fit1 = arima(stock_close, order = c(3,0,4))
fit2 = arima(stock_close, order = c(3,0,5))
fit3 = arima(stock_close, order = c(3,0,6))
fit4 = arima(stock_close, order = c(3,1,7))
fit5 = arima(stock_close, order = c(3,1,8))
fit6 = arima(stock_close, order = c(3,1,9))
fit7 = arima(stock_close, order = c(4,1,4))
fit8 = arima(stock_close, order = c(4,1,5))
fit9 = arima(stock_close, order = c(4,1,6))
fit10 = arima(stock_close, order = c(4,0,7))
fit11 = arima(stock_close, order = c(5,0,4))
fit12 = arima(stock_close, order = c(3,0,5))
fit13 = arima(stock_close, order = c(2,2,4))
fit14 = arima(stock_close, order = c(4,2,5))
fit15 = arima(stock_close, order = c(2,3,2))
fit16 = arima(stock_close, order = c(2,3,3))
fit17 = arima(stock_close_ts, order = c(3,3,5))
fit18 = arima(stock_close_ts, order = c(4,3,5))
fit19 = arima(stock_close_ts, order = c(5,3,5))
fit20 = arima(stock_close_ts, order = c(3,4,3))
fit21 = arima(stock_close_ts, order = c(3,4,4))
fit22 = arima(stock_close_ts, order = c(3,4,5))
fit23 = arima(stock_close_ts, order = c(3,4,6))
fit24 = arima(stock_close_ts, order = c(3,4,7))
fit25 = arima(stock_close_ts, order = c(4,4,3))
fit26 = arima(stock_close_ts, order = c(4,4,4))
fit27 = arima(stock_close_ts, order = c(4,4,5))
fit28 = arima(stock_close_ts, order = c(4,4,6))
fit29 = arima(stock_close_ts, order = c(4,4,7))
fit30 = arima(stock_close_ts, order = c(5,4,3))
fit31 = arima(stock_close_ts, order = c(5,4,4))
fit32 = arima(stock_close_ts, order = c(5,4,5))
fit33 = arima(stock_close_ts, order = c(5,4,6))
fit34 = arima(stock_close_ts, order = c(4,5,8))
fit35 = arima(stock_close_ts, order = c(6,5,8))
fit36 = arima(stock_close_ts, order = c(6,6,7))

length_of_forecast = 130

fcast1 <- forecast(fit1, h=length_of_forecast)
fcast2 <- forecast(fit2, h=length_of_forecast)
fcast3 <- forecast(fit3, h=length_of_forecast)
fcast4 <- forecast(fit4, h=length_of_forecast)
fcast5 <- forecast(fit5, h=length_of_forecast)
fcast6 <- forecast(fit6, h=length_of_forecast)
fcast7 <- forecast(fit7, h=length_of_forecast)
fcast8 <- forecast(fit8, h=length_of_forecast)
fcast9 <- forecast(fit9, h=length_of_forecast)
fcast10 <- forecast(fit10, h=length_of_forecast)
fcast11 <- forecast(fit11, h=length_of_forecast)
fcast12 <- forecast(fit12, h=length_of_forecast)
fcast13 <- forecast(fit13, h=length_of_forecast)
fcast14 <- forecast(fit14, h=length_of_forecast)
fcast15 <- forecast(fit15, h=length_of_forecast)
fcast16 <- forecast(fit16, h=length_of_forecast)
fcast17 <- forecast(fit17, h=length_of_forecast)
fcast18 <- forecast(fit18, h=length_of_forecast)
fcast19 <- forecast(fit19, h=length_of_forecast)
fcast20 <- forecast(fit20, h=length_of_forecast)
fcast21 <- forecast(fit21, h=length_of_forecast)
fcast22 <- forecast(fit22, h=length_of_forecast)
fcast23 <- forecast(fit23, h=length_of_forecast)
fcast24 <- forecast(fit24, h=length_of_forecast)
fcast25 <- forecast(fit25, h=length_of_forecast)
fcast26 <- forecast(fit26, h=length_of_forecast)
fcast27 <- forecast(fit27, h=length_of_forecast)
fcast28 <- forecast(fit28, h=length_of_forecast)
fcast29 <- forecast(fit29, h=length_of_forecast)
fcast30 <- forecast(fit30, h=length_of_forecast)
fcast31 <- forecast(fit31, h=length_of_forecast)
fcast32 <- forecast(fit32, h=length_of_forecast)
fcast33 <- forecast(fit33, h=length_of_forecast)
fcast34 <- forecast(fit34, h=length_of_forecast)
fcast35 <- forecast(fit35, h=length_of_forecast)
fcast36 <- forecast(fit36, h=length_of_forecast)

plot(fcast1)
plot(fcast2)
plot(fcast3)
plot(fcast4)
plot(fcast5)
plot(fcast6)
plot(fcast7)
plot(fcast8)
plot(fcast9)
plot(fcast10)
plot(fcast11)
plot(fcast12)
plot(fcast13)
plot(fcast14)
plot(fcast15)
plot(fcast16)
plot(fcast17)
plot(fcast18)
plot(fcast19)
plot(fcast20)
plot(fcast21)
plot(fcast22)
plot(fcast23)
plot(fcast24)
plot(fcast25)
plot(fcast26)
plot(fcast27)
plot(fcast28)
plot(fcast29)
plot(fcast30)
plot(fcast31)
plot(fcast32)
plot(fcast33)
plot(fcast34)
plot(fcast35)
plot(fcast36)


lnstock<-log(stock_close[1,96])
lnstock

stock_ma_5<-ma(stock_close, 5)
stock_ma_6<-ma(stock_close, 6)
stock_ma_7<-ma(stock_close, 7)
stock_ma_8<-ma(stock_close, 8)
stock_ma_9<-ma(stock_close, 9)
stock_ma_10<-ma(stock_close, 10)
stock_ma_11<-ma(stock_close, 11)
stock_ma_12<-ma(stock_close, 12)



tsdisplay(residuals(fit1), lag.max=40, main='(0,1,1)')